### ISSUE TITLE
VT sometimes stops all hooks when deleting torrent

### ISSUE THREAD

**Issue by Larsluph** [WDaan/VueTorrent#860]
I have this error when I sometimes delete a torrent which causes everything to completely stop working until a refesh. I think it comes from the fact that some processing are done when the torrents are updating, so the hash doesn't exist anymore when looking it up to compute selection size.

```
TypeError: Cannot read properties of undefined (reading 'size')
    at index.ada30567.js:737:17546
    at Array.map (<anonymous>)
    at s.<anonymous> (index.ada30567.js:737:17537)
    at s.torrentCountString (index.ada30567.js:774:650713)
    at t.get (vue.7fbf5199.js:5:22570)
    at t.evaluate (vue.7fbf5199.js:5:23570)
    at s.torrentCountString (vue.7fbf5199.js:5:37192)
    at s.Ggu (index.ada30567.js:774:652377)
    at t._render (vue.7fbf5199.js:5:17740)
    at s.n (vue.7fbf5199.js:5:26375)
```
which when looking at the source points to these lines in VT.
https://github.com/WDaan/VueTorrent/blob/810fe882beca4894e6ee3abd5154139ef8a8f5f5/src/store/getters.ts#L23-L28

**Comment by Larsluph** [comment]
Issue still occurs
